import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideMenu from "@/components/global/side-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          "font-geist-sans container bg-slate-900 dark",
          GeistSans.className,
        )}
      >
        <div className='lg:px-24 mx-auto flex flex-col md:flex-row gap-4 w-full h-full pt-24 '>
          <SideMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
